# Generated by Django 6.0.4 on 2026-05-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=100, verbose_name='Категория')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование товара', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Приложите фото товара', null=True, upload_to='products/photo', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену товара', max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Введите дату создания', verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, help_text='Введите дату последнего изменения', verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'category', 'created_at', 'updated_at'],
            },
        ),
    ]
