# Generated by Django 6.0.3 on 2026-04-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price_per_purchase",
            new_name="price",
        ),
    ]
